# fly.toml app configuration file for client-project-professional-lunch
# Updated to resolve port mismatch issue.

app = "client-project-professional-lunch"
primary_region = "ord"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
